let start = document.querySelector('#start'),
    budgetValue = document.querySelector('.budget-value'),
    daybudgetValue = document.querySelector('.daybudget-value'),
    levelValue = document.querySelector("level-value"),
    expensesValue = document.querySelector("expenses-value"),
    optionalexpensesValue = document.querySelector("optionalexpenses-value"),
    incomeValue = document.querySelector("income-value"),
    monthsavingsValue = document.querySelector("monthsavings-value"),
    yearsavingsValue = document.querySelector("yearsavings-value"),
    yearValue = document.querySelector("year-value"),
    monthValue = document.querySelector("month-value"),
    dayValue = document.querySelector("day-value"),
    expensesItem = document.getElementsByClassName('expenses-item'),
    expensesBtn = document.getElementsByTagName('button')[0],
	optionalExpensesBtn = document.getElementsByTagName('button')[1],
    countBtn = document.getElementsByTagName('button')[2],
    optionalExpensesItem = document.querySelectorAll('.optionalexpenses-item'),
    incomeItem = document.querySelector('.choose-income'),
	checkSavings = document.querySelector('#savings'),
	sumValue = document.querySelector('.choose-sum'),
    percentValue = document.querySelector('.choose-percent');

console.log(expensesItem);